### ISSUE TITLE
Tiny video filter button in portrait mode

### ISSUE THREAD

**Issue by marvin1099** [devhyper/open-video-editor#1]
It sees the video filter button (the one that looks like a gallery icon) is tiny in portrait mode while in landscape its fine.
Also nice work making basikly the first foss video editor, just these simple edit options, are so powerfull.
Here are some screenshots
First in portrait orientation (button hard to see and press)
![Screenshot_20231231-222505_Open Video Editor](https://github.com/devhyper/open-video-editor/assets/40715852/90efb1e3-e8df-4f2d-a46e-269b53645a9a)
Then in landscape orientation (button easy to see and press)
![Screenshot_20231231-222648_Open Video Editor](https://github.com/devhyper/open-video-editor/assets/40715852/1824e850-7afe-4e76-8e4b-7ba5044f0d13)

**Comment by devhyper** [comment]
Thanks for sending this, should be fixed now.
Try this build and let me know: 
[app-debug.zip](https://github.com/devhyper/open-video-editor/files/13802466/app-debug.zip)

**Comment by marvin1099** [comment]
Jep works like a charm.
