### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Cwpute** [devhyper/open-video-editor#11]
Having this app localized will really help those that don't speak english so well.

We could crowdsource the localization using hosted tools like Crowdin or Weblate. I've extensively used them, and as someone who isn't used to version control and git, it is a fantastic way to get into localization easily without much hassle!

I could personally help with the french translation :)

**Comment by Cwpute** [comment]
As a side note, you will have to take localization into account when adressing responsive UI changes (#10), as it implies text lenght will highly vary depending on the choosed language.

**Comment by devhyper** [comment]
@Cwpute Weblate is up: https://hosted.weblate.org/projects/open-video-editor/android

**Comment by Cwpute** [comment]
just translated to french ;)
i'm skeptical about translating the app name as well, it would make it hard to consistently find while searching online whichever language you're searching in. and it doesn't sound as good in french :p
