### ISSUE TITLE
Add mp3,mp4 extract feature

### ISSUE THREAD

**Issue by heberjeur** [devhyper/open-video-editor#18]
Hi, can you add mp3 and mp4 extract feature, it's useful more than others

**Comment by BinTianqi** [comment]
You can select "audio only" or "video only" here.
![Screenshot_20240107-185833_Open Video Editor](https://github.com/devhyper/open-video-editor/assets/146811279/85b5d2a3-38e6-418a-8a30-b4039d2a0a3e)

**Comment by heberjeur** [comment]
There are no options to export mp3 or mp4

![Screenshot_20240107-150621_Open Video Editor](https://github.com/devhyper/open-video-editor/assets/11852634/5ebd4476-5d67-4466-b69f-b31515127799)
![Screenshot_20240107-150606_Open Video Editor](https://github.com/devhyper/open-video-editor/assets/11852634/d445abee-b4a6-4f9f-a7ee-a5e9058d539e)

**Comment by BinTianqi** [comment]
video type:
video/avc equals h.264 and h.264 equals .mp4 format.

Although there is no mp3 format, mp4a and 3gpp are common formats and you can play them on many platforms.

**Comment by devhyper** [comment]
Media3 Transformer only supports MP4 output: https://developer.android.com/media/media3/transformer/supported-formats
