### ISSUE TITLE
add new features 

### ISSUE THREAD

**Issue by rajarshikhatua100** [devhyper/open-video-editor#19]
add new features from these apps - 

1. https://play.google.com/store/apps/details?id=com.luma_touch.lumafusion
2. https://play.google.com/store/apps/details?id=com.shallwaystudio.nodevideo
3. https://play.google.com/store/apps/details?id=com.nexstreaming.app.kinemasterfree
4. https://play.google.com/store/apps/details?id=com.frontrow.vlog
5. https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.producer

**Comment by Cwpute** [comment]
Hey there @rajarshikhatua100 
Please be more precise with your requests. Your previous message is just linking to other apps without any context or specifics.

Which features do you want to see implemented from those apps?
Please close this issue, and open 1 issue per feature request. This will greatly help maintainers understand your request, and help them eventually implement your requests if they see fit.

Thanks :)
