### ISSUE TITLE
Wonky number display on smaller screen sizes.

### ISSUE THREAD

**Issue by MichaelDevon** [devhyper/open-video-editor#23]
![Screenshot_20240110-081208](https://github.com/devhyper/open-video-editor/assets/151486478/de1fa9d1-3a3a-49bb-93dc-73a2c8a4ae8c)

The frame numbers split in half which is confusing.

i suggest moving some elements around to get some more space.

**Comment by devhyper** [comment]
Frame number now truncates with ellipses, dialog is shown upon clicking frame showing full frame numbers and allowing seeking to a specific frame number. 
9b0321d
