### ISSUE TITLE
[feature request] Lossless trimming/cutting mode

### ISSUE THREAD

**Issue by plum7x** [devhyper/open-video-editor#26]
A feature to lossless cut video that is very useful for save time and storage by rough-cutting and keep quality.

And to avoid the broken beginning of output video, use the keyframe as actually starting point that closest to the starting point by user specified.

In Windows, we have LosslessCut, but I don't see any app with this feature in Android.

**Comment by RustoMCSpit** [comment]
https://github.com/mifi/lossless-cut gplv2 license

**Comment by devhyper** [comment]
641f071
