### ISSUE TITLE
undo grey scale

### ISSUE THREAD

**Issue by RustoMCSpit** [devhyper/open-video-editor#32]
please design filters non-destructively until export

**Comment by RustoMCSpit** [comment]
closed as i made a new, broader issue

**Comment by RustoMCSpit** [comment]
ths doesnt work? @devhyper im confused, i thought you said we had non-destructive editing

**Comment by devhyper** [comment]
> ths doesnt work? @devhyper im confused, i thought you said we had non-destructive editing

Click this:
![Screenshot 2024-03-14 192242](https://github.com/devhyper/open-video-editor/assets/57877914/b7ad87c3-bf94-463c-9d5d-4ba0500aacc5)

**Comment by RustoMCSpit** [comment]
> > ths doesnt work? @devhyper im confused, i thought you said we had non-destructive editing
> 
> Click this: ![Screenshot 2024-03-14 192242](https://private-user-images.githubusercontent.com/57877914/313047339-b7ad87c3-bf94-463c-9d5d-4ba0500aacc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDE2ODgsIm5iZiI6MTcxMDU0MTM4OCwicGF0aCI6Ii81Nzg3NzkxNC8zMTMwNDczMzktYjdhZDg3YzMtYmY5NC00NjNjLTlkNWQtNGJhMDUwMGFhY2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDIyMjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZjQ2ODUwZDAxZjRmYmQ3MjljMWM3OGE5YzM3NDkyZTZlZTIwM2Q5YzU3Yjc5MjI2ZmU3NTc2YjJhY2E2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RD2V3pM6DbUC8x56WfSswFey2yZ0_yuaum4vXoR6Bb8)

ahhh, hitting greyscale itself doesnt undo it so i assume it's basing it off of a timeframe. regardless, theres no way to undo the greyscale mid-video. so if i greyscale at 5 seconds and then want to colorscale at 12 seconds i cant. does that make sense?

**Comment by RustoMCSpit** [comment]
> please design filters non-destructively until export

ignore this, it is non-destructive

**Comment by RustoMCSpit** [comment]
like yk how you hit invert colors again and it goes back to normal, but grey doesnt. either have everything work  as i described above or have it do as you do with the invert colors, having two standards is bad

**Comment by devhyper** [comment]
Yeah sorry for the confusion. When you click the filter twice it will just apply the filter again, so invert colors just inverts the already inverted colors back. I'll leave it as is now, because when composition previewing lands in Media3, I will implement the ability to specify filter lengths. This will also allow for the grayscale certain part and invert certain part you mentioned.

**Comment by RustoMCSpit** [comment]
> Yeah sorry for the confusion. When you click the filter twice it will just apply the filter again, so invert colors just inverts the already inverted colors back. I'll leave it as is now, because when composition previewing lands in Media3, I will implement the ability to specify filter lengths. This will also allow for the grayscale certain part and invert certain part you mentioned.

when will that be implemwnted and what is it simply?

**Comment by devhyper** [comment]
Basically the app uses the Android Media3 library as a backend to process and play the video. Currently, the library has this thing called Composition, which allows adding multiple videos together, cutting them into segments, adding effects to certain segments, etc. However the player in the library cannot play this composition yet, they are working on it in their main branch though. My guess is that it will come in their library version 1.4.

#55

**Comment by RustoMCSpit** [comment]
> Basically the app uses the Android Media3 library as a backend to process and play the video. Currently, the library has this thing called Composition, which allows adding multiple videos together, cutting them into segments, adding effects to certain segments, etc. However the player in the library cannot play this composition yet, they are working on it in their main branch though. My guess is that it will come in their library version 1.4.
> 
> #55

how can yoy put stuff in the next milestone if thatll take months to come out

**Comment by devhyper** [comment]
The stuff in the milestones don't require composition. Everything that does is tracked by #55
