### ISSUE TITLE
save project to work on later

### ISSUE THREAD

**Issue by RustoMCSpit** [devhyper/open-video-editor#33]

**Comment by RustoMCSpit** [comment]
project should be a file on android so it isnt locked to the app

**Comment by RustoMCSpit** [comment]
no idea if there is a standard for stuff like this so checj that out

**Comment by devhyper** [comment]
d392979

**Comment by devhyper** [comment]
> > [d392979](https://github.com/devhyper/open-video-editor/commit/d392979fe615d4b30c99010b8e57d61e6b54a5af)
> 
> is the project a file in the file explorer?

Yes, project file is saved to disk, viewable in file explorer.
