### ISSUE TITLE
non-destructive editing

### ISSUE THREAD

**Issue by RustoMCSpit** [devhyper/open-video-editor#38]

**Comment by RustoMCSpit** [comment]
https://github.com/devhyper/open-video-editor/issues/32

ive decided this needs to be a broader, over-all design issue. the app shouldnt be destructive and it's best to work on that as it is just new rather than designing it for ywars in a way that prevents this

**Comment by RustoMCSpit** [comment]
@devhyper i think this should be prioritised as going further without it will fuck the editor in the long and short run but it's your call 🙏

**Comment by devhyper** [comment]
> @devhyper i think this should be prioritised as going further without it will fuck the editor in the long and short run but it's your call 🙏

By non-destructive editing do you mean being able to reverse changes? This should already be implemented.

**Comment by RustoMCSpit** [comment]
> > @devhyper i think this should be prioritised as going further without it will fuck the editor in the long and short run but it's your call 🙏
> 
> By non-destructive editing do you mean being able to reverse changes? This should already be implemented.

how do you un-do greyscale?

**Comment by devhyper** [comment]
Click the layers icon, then click the trash icon next to grayscale.

**Comment by RustoMCSpit** [comment]
> Click the layers icon, then click the trash icon next to grayscale.

ahh i see, if this is the case for all effects close this
