### ISSUE TITLE
[Feature Request] Change Video Speed

### ISSUE THREAD

**Issue by CaidenBlock** [devhyper/open-video-editor#5]
The ability to change Timescale without using ffmpeg in termux would be huge (hardware vs software)

https://developer.android.com/reference/androidx/media3/effect/SpeedChangeEffect might work well enough, though it says it doesn't[ drop frames](https://developer.android.com/reference/androidx/media3/effect/FrameDropEffect)

I'll look into this more at a later date, but I'm pretty far away from my desktop atm

**Comment by devhyper** [comment]
Unfortunately Media3 doesn't support previewing these effects, so I have added this to the export settings.
