### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [devhyper/open-video-editor#53]
https://hosted.weblate.org/projects/open-video-editor/android/#information says
GPLv3`-only`, and usually it is the case that people want `-or-later`.
`-or later` allows for more freedom without negotiating with each individual translator.
The root repo here doesn't specify one way or the other.

It can be changed in 

https://hosted.weblate.org/settings/open-video-editor/android/
https://hosted.weblate.org/settings/open-video-editor/glossary/

**Comment by devhyper** [comment]
Thanks, license has been changed.
Weblate should be fully setup and unlocked soon.
