### ISSUE TITLE
Release on F-Droid?

### ISSUE THREAD

**Issue by olof-nord** [devhyper/open-video-editor#6]
I saw the app was available per the izzyonfdroid store. Any plans of also add it to f-droid?

**Comment by devhyper** [comment]
https://gitlab.com/fdroid/rfp/-/issues/2615

**Comment by adumelie** [comment]
Don't want to open up an issue just to say this, but this is almost exactly what I was looking for ! Good work !

**Comment by ClockGen** [comment]
Merge request to fdroiddata: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14346

**Comment by ClockGen** [comment]
Merge request has been merged https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14346
The app will probably be available in the next f-droid server build run or two.

**Comment by nichobi** [comment]
The app is available [on F-Droid](https://f-droid.org/en/packages/io.github.devhyper.openvideoeditor/) since Monday and was also given a shoutout in the latest [This Week In F-Droid](https://f-droid.org/2024/01/25/twif.html)!

**Comment by IzzySoft** [comment]
Congrats to that :partying_face: But honestly, the app description shown is … well, let's say "less than ideal":

![image](https://github.com/devhyper/open-video-editor/assets/6781438/340b8d30-2d83-4012-adbe-20b9a5e0907a)

looks like "not much love put into". Which is btw why I ignore the `full_description.txt` for my repo:

![image](https://github.com/devhyper/open-video-editor/assets/6781438/4004afe2-cae2-4b9a-a9ce-9723659b0668)

Want to have mine?

```html
<p><i>Open Video Editor</i> lets you edit your videos. It supports HDR and allows to apply filters. With this app you also can trim, scale, and rotate your videos or even grayscale them. It is also possible to use this app to extract audio from a video, to convert a HDR video to SDR, or to convert it to a different format.</p>
```

(and yes, goes all on a single line, no line breaks as F-Droid converts those to `<br>` no matter what).

Would you please? :smiley: In turn I'd keep your app in my repo (as long as the APK size doesn't grow too much), and enable pulling your (then updated) `full_description.txt` along with each update. Deal?

**Comment by devhyper** [comment]
> looks like "not much love put into". Which is btw why I ignore the `full_description.txt` for my repo
Yep, probably should have wrote some more stuff.
> Would you please? 😃 In turn I'd keep your app in my repo (as long as the APK size doesn't grow too much), and enable pulling your (then updated) full_description.txt along with each update. Deal?
Sure, I'll add the description now and make a release over the weekend when I get some more time. Thanks!

**Comment by IzzySoft** [comment]
Thanks! Enabled it here for my "fastlane pulling", so it will be checked now as well when pulling updates.
