### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [devhyper/open-video-editor#63]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6417503136#L426

while the APK content files of CI (https://gitlab.com/fdroid/fdroiddata/-/jobs/6417503136/artifacts/file/tmp/io.github.devhyper.openvideoeditor_5.apk) and your release (https://github.com/devhyper/open-video-editor/releases/tag/v1.1.1) are identical, the actual structure of the archive is padded very different.

Did you change some tooling, the way you build your APKs?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/1a93f92338965f392d92414f49a26b7182a829b7

**Comment by devhyper** [comment]
Only changes were updating Android Studio and the build tools to the latest version, and adding the ffmpeg-kit dependency. Could these have something to do with that?

**Comment by mario0318** [comment]
> Only changes were updating Android Studio and the build tools to the latest version, and adding the ffmpeg-kit dependency. Could these have something to do with that?

Is this also the reason the latest apk release is massive compared to earlier ones?

**Comment by devhyper** [comment]
> > Only changes were updating Android Studio and the build tools to the latest version, and adding the ffmpeg-kit dependency. Could these have something to do with that?
> 
> Is this also the reason the latest apk release is massive compared to earlier ones?

Size difference is because of the addition of ffmpeg, I swapped to the min version so the next release will be 10 MB less.

**Comment by devhyper** [comment]
> I keep rebuilding...
> 
> reading https://github.com/obfusk/reproducible-apk-tools?tab=readme-ov-file#inplace-fixpy _"NB: build-tools 31.0.0 and 32.0.0 are skipped because [their zipalign is broken](https://android.googlesource.com/platform/build/+/df73d1b4733b8b3cdfd96199018455026ba8d9d2); --page-size requires build-tools >= 35.0.0-rc1."_ made me think that this might be the issue somehow, because the difference is massive padding in the APK
> 
> @mario0318 fyi ^^^ not libs differences
> 
> @devhyper wonder how many `build-tools` do you have installed and which ones?

Looks like I have 34.0.0 installed, the build has always used that since that was the minimum version required for the android gradle plugin. Turns out the updated 35 rc was not used.

**Comment by devhyper** [comment]
Just realized that gradle was updated from 8.2.1 to 8.4, that is probably it.

**Comment by devhyper** [comment]
Building with gradle 8.2.1 makes the apk size closer to the fdroid one, but it is still different. This is due to ffmpeg then? Is is possible to disable reproducible builds on fdroid?

**Comment by licaon-kter** [comment]
It's easier to just attach an APK and point me to a commit so I can check.

**Comment by devhyper** [comment]
d0801dc
[app-release.zip](https://github.com/devhyper/open-video-editor/files/14688267/app-release.zip)

**Comment by licaon-kter** [comment]
Same error, but oddly the APKs are 20Mb smaller now, wonder why...

**Comment by devhyper** [comment]
Apks are smaller because I changed ffmpeg to min version. I think I need to add 35 rc to the build file.

**Comment by devhyper** [comment]
130152e
[app-release.zip](https://github.com/devhyper/open-video-editor/files/14716539/app-release.zip)
Added build tools 35.0.0 rc2 to build.gradle, the warning should disappear now.
@licaon-kter

**Comment by devhyper** [comment]
@licaon-kter

**Comment by licaon-kter** [comment]
Didn't got a chance to retry, will do asap

**Comment by linsui** [comment]
1.1.2 has the same problem.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15112 Fixed.

**Comment by obfusk** [comment]
> https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15112 Fixed.

Wow. You still didn't realise you've simply been calling `inplace-fix.py` with the wrong parameters all this time?

You could have just replaced the incorrect use of `--zipalign` with `--page-align` (or `--page-size 16` for v1.1.1 since it used AGP >= 8.3 before it was downgraded again in v1.1.2 and the alignment changed back to 4K pages) months ago instead of taking ages to come up with that hack to work around the fact you've been calling my RB tools with the wrong parameters and thus getting the ZIP alignment wrong on your end all this time. I guess F-Droid could use an RB expert.

**Comment by linsui** [comment]
> You could have just replaced the incorrect use of --zipalign with --page-align (or --page-size 16 for v1.1.1 since it used AGP >= 8.3 before it was downgraded again in v1.1.2 and the alignment changed back to 4K pages) months ago instead of taking ages to come up with that hack to work around the fact you've been calling my RB tools with the wrong parameters and thus getting the ZIP alignment wrong on your end all this time.

Tried with 16 and 64 but it doesn't work.

> I guess F-Droid could use an RB expert.

No need to guess since you were the only RB expert.

**Comment by obfusk** [comment]
> Tried with 16 and 64 but it doesn't work.

Try 4. It works.

**Comment by linsui** [comment]
Trying now.

**Comment by obfusk** [comment]
And 4 has been the default for ages (AGP < 8.3). You just need to actually use page alignment by passing `--page-align` or `--page-size`, which you haven't been doing.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15113 Fixed, thanks!

> You just need to actually use page alignment by passing --page-align or --page-size, which you haven't been doing.

I don't know this arg before yesterday and I just realize that page align is not enabled by default. :shrug:

**Comment by licaon-kter** [comment]
I've tested align 4 for https://github.com/elastic-rock/KeepScreenOn/issues/26 and there it needed 16 heh

Will need to juggle all these values then when the next one fails, based on AGP version.

Thanks

**Comment by obfusk** [comment]
> Will need to juggle all these values then when the next one fails, based on AGP version.

Yeah, you need to know what ZIP alignment parameters should be used to match the upstream APK. Google changing the defaults complicates that. But you always needed `--page-align` to properly align uncompressed `.so` files.

FYI I recommend using `--internal` to always use the built-in pure-Python `zipalign.py` instead of relying on the code to automatically detect a suitable version from `build-tools` (and the Debian package doesn't support different page sizes).

**Comment by obfusk** [comment]
> No need to guess since you were the only RB expert.

Then maybe F-Droid shouldn't have forced its only RB expert to resign :woman_shrugging:
Good luck keeping things running.

**Comment by licaon-kter** [comment]
hmm https://gitlab.com/fdroid/fdroiddata/-/jobs/7729208261#L1695

tried locally with `zipalign.py --page-size 16 --pad-like-apksigner --replace unaligned.apk $$OUT$$` but did not help :cry:

**Comment by obfusk** [comment]
You're still using my tooling wrong, just trying random things without understanding how it works. Because it works perfectly fine if you don't screw up the padding by using `--pad-like-apksigner` when the upstream APK doesn't have `apksigner` padding (which is clearly the case here). The IzzyOnDroid rebuilder had no issues confirming v1.1.3 is reproducible yesterday.

**Comment by linsui** [comment]
Thank you, RB expert. :) https://gitlab.com/fdroid/fdroiddata/-/commit/2c466ac3a017605fdeeb86d72c725089ab3e127c
