### ISSUE TITLE
Crash on opening video via edit or share

### ISSUE THREAD

**Issue by tomaszk8266** [devhyper/open-video-editor#70]
When I'm trying to open a video from edit/share button (for example in gallery) the app crashes.

**Comment by variety754** [comment]
Same happens for me with Fossify Gallery

**Comment by HighPriest** [comment]
This feature used to work fine like... 2 months ago, so I would suspect the issue being on Fossify Gallery side. I'll check in a moment if older versions of Gallery work.

**Comment by devhyper** [comment]
It looks like if Fossify Gallery is given permission to access all files, then the intent sent has the correct permissions and no crash occurs. If Fossify Gallery only has media permissions, then the intent sent doesn't have the permissions required for some reason.
