### ISSUE TITLE
App is not listed in "open with" dialog

### ISSUE THREAD

**Issue by cryofault** [devhyper/open-video-editor#73]
Great app but it isn't listed as being able to handle .mp4 files when using "open with" and cannot be set as my default video editor from gallery as a result.

![Screenshot_20240423-031226_IntentResolver_1](https://github.com/devhyper/open-video-editor/assets/25939455/05e1a391-01c6-413d-82a8-2ca027ebbb7b)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/devhyper/open-video-editor/issues/73#issue-2258250167

It is for me, using https://apt.izzysoft.de/fdroid/repo/org.fossify.gallery_7.apk:

> ![Screenshot_20240423-101653](https://github.com/devhyper/open-video-editor/assets/42837531/42c8d356-4740-4c35-94b9-e79ed88d9800)

**Comment by cryofault** [comment]
> > [#73 (comment)](https://github.com/devhyper/open-video-editor/issues/73#issue-2258250167)
> 
> It is for me, using https://apt.izzysoft.de/fdroid/repo/org.fossify.gallery_7.apk:
> 
> > ![Screenshot_20240423-101653](https://private-user-images.githubusercontent.com/42837531/324772234-42c8d356-4740-4c35-94b9-e79ed88d9800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzM2NzYsIm5iZiI6MTcxMzk3MzM3NiwicGF0aCI6Ii80MjgzNzUzMS8zMjQ3NzIyMzQtNDJjOGQzNTYtNDc0MC00YzM1LTk0YjktZTc5ZWQ4OGQ5ODAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE1NDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMzE5NmE4NzdkMDlmZjE3MDZhYTRhMmQ3OTdiMDRiZWVmZDZmOTExNGIzMDFhOTk4MWEwN2QyYzY1YjBmNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kIrDMR8czHl514i-sf0L1w5j76omMwNB8F_oo2rYcxY)

I'm running Lineage OS 21/Android 14 and with fossify gallery it still does not appear in the open with dialog but if I hit the edit button on the bottom that seemingly makes an attempt. If the edit button was working that'd be ideal but instead open video editor seemingly just crashes instantly. If I tap the button repeatedly nothing happens until I suddenly get this popup:

![Screenshot_20240424-103918_Gallery_1](https://github.com/devhyper/open-video-editor/assets/25939455/06871792-77f6-4f9b-a281-136494b46843)

**Comment by devhyper** [comment]
#70 crash fixed
