### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [devhyper/open-video-editor#75]
And all files in the apk are identical. Only the zip metadata is different. Any idea?

**Comment by devhyper** [comment]
Did you test 1.1.2, the reproducible-build-tools warning referenced in #63 should have been fixed by updating build tools.

**Comment by SRC267** [comment]
> Did you test 1.1.2, the reproducible-build-tools warning referenced in #63 should have been fixed by updating build tools. 

Also, noticed it's not updated in the playstore, I'm guessing that's just a delay in the delivery process?

**Comment by devhyper** [comment]
> > Did you test 1.1.2, the reproducible-build-tools warning referenced in #63 should have been fixed by updating build tools.
> 
> Also, noticed it's not updated in the playstore, I'm guessing that's just a delay in the delivery process?

Yeah play store is awaiting approval

**Comment by linsui** [comment]
Oh, let's continue in the old issue.
